# Sample .travis.yml for R projects +
# https://github.com/travis-ci/travis-ci/issues/5775

language: r
r: 
 - bioc-devel 
 ## - devel  ## travis issues with /bin/bash: line 2: -shared: command not found and /bin/bash: I/home/travis/R-bin/lib/R/include: No such file or directory
 ## - patched  ## not needed paranoia: this is what I use locally. And it does not find the r-patched file
 

warnings_are_errors: true

sudo: required

cache: packages

r_github_packages:
  - jimhester/covr

# https://github.com/travis-ci/travis-ci/issues/6587
# Set CXX1X for R-devel, as R-devel does not detect CXX1X support for gcc 4.6.3,
# this was causing hunspell installation to fail
before_install:
  - if [[ "$TRAVIS_R_VERSION_STRING" = 'bioc-devel' ]]; then mkdir ~/.R && echo 'CXX1X=g++ -std=c++0x -g -O2 -fPIC' > ~/.R/Makevars; fi

install:
  - Rscript -e 'install.packages(c("devtools","knitr","testthat","roxygen2","Oncotree","rmarkdown","bookdown", "withr", "covr"));source("http://bioconductor.org/biocLite.R");options(repos=biocinstallRepos());biocLite(c("BiocStyle"));devtools::install_deps("OncoSimulR")'

# withr failing because of a broken dependency on "later"
# install:
#   - Rscript -e 'install.packages(c("devtools","knitr","testthat","roxygen2","Oncotree","rmarkdown","bookdown"));source("http://bioconductor.org/biocLite.R");options(repos=biocinstallRepos());biocLite(c("BiocStyle"));devtools::install_deps("OncoSimulR");devtools::install_github("jimhester/withr");devtools::install_github("jimhester/covr")'


before_script:
   - R CMD build --keep-empty-dirs OncoSimulR
script:
   - R CMD check OncoSimulR_*.tar.gz

after_success:
  - Rscript -e 'library(covr); options(covr.flags = c(CPPFLAGS = "-O3 -g --coverage", CXX1XFLAGS = "-O3 -g --coverage", CXXFLAGS = "-O3 -g --coverage", CFLAGS = "-O3 -g --coverage", LDFLAGS = "--coverage")); covr::codecov("OncoSimulR")'



notifications:
  email:
    on_success: change
    on_failure: change



##  I prefer to mimic the build and check dance
## - Rscript -e 'devtools::check("OncoSimulR", document = FALSE, force_suggests = TRUE)'


## Remember to fix the file paths as:

## R/::OncoSimulR/R
## src/::OncoSimulR/src

##  so that codecov info is shown.
