comment: false
## comment:
##  layout: header, changes, diff
coverage:
  fixes:
  - R/::OncoSimulR/R
  - src/::OncoSimulR/src
##  ignore:
##  - R/::OncoSimulR/R
##  - src/::OncoSimulR/src
##  status: {}
